version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: maja
      POSTGRES_PASSWORD: maja
      POSTGRES_DB: baza
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maja -d baza"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


