version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: maja
      POSTGRES_PASSWORD: maja
      POSTGRES_DB: baza
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maja -d baza"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command:
      - postgres
      - -c
      - listen_addresses=*

  app:
    build: .
    container_name: projekt
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/projekt
    environment:
      DATABASE_URL: postgresql://maja:maja@my_postgres:5432/baza
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  postgres_data:


